name: avia_tickets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
  fonts:
    - family: Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
